### ISSUE TITLE
MS Planner config sync - Use Plan/Board name 

### ISSUE THREAD

**Issue by moshloop** [flanksource/incident-commander#150]
It should only create a single config_item per board and then update it on subsequent runs. 
Plan id should be the external_id for deduplication

**Comment by yashmehrotra** [comment]
@moshloop Currently the name field is `client_id` of the MSPlanner Client provided by Microsoft, the problem with using plan_name as the name is that there can be multiple plans associated with one client and no way for us to determine what plan needs to be used.

Similarly, we are using team_id as the external_id for deduplication since (config type, external_id) would always be unique in that case.

A workaround for this could be that we use `values` object here, where the Board in case of Jira and Plan in case MS Planner is already fixed, this way the config name would be the one the teams actually use, I'll be going ahead with that approach

**Comment by yashmehrotra** [comment]
Related to #153
